environment:
  matrix:
    - PYTHON_VERSION: "27"
      NODEJS_VERSION: "4.6"
      BROWSER: "PhantomJS"
    - PYTHON_VERSION: "33"
      NODEJS_VERSION: "4.6"
      BROWSER: "Firefox"
    - PYTHON_VERSION: "34"
      NODEJS_VERSION: "6.9"
      BROWSER: "PhantomJS"
    - PYTHON_VERSION: "35"
      NODEJS_VERSION: "6.9"
      BROWSER: "Firefox"
    - PYTHON_VERSION: "36"
      NODEJS_VERSION: "7.4"
      BROWSER: "IE"
matrix:
  allow_failures:
    - BROWSER: "IE"

install:
  - "SET PATH=C:\\PYTHON%PYTHON_VERSION%\\Scripts;%PATH%"
  - "SET PATH=C:\\PYTHON%PYTHON_VERSION%;%PATH%"
  - ps: Install-Product node $env:NODEJS_VERSION
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"

  - pip install coverage calmjs
  - pip install flask
  - pip install -e git+https://github.com/calmjs/nunja.git#egg=nunja
  - python setup.py develop
  # as uvloop is NOT available on Windows.
  - "SET SANIC_NO_UVLOOP=no"
  - ps: >-
      if ($env:PYTHON_VERSION -ge '35') {
        pip install --no-use-wheel sanic
        pip install sanic aiohttp;
      }

test_script:
  - coverage run --include=src\* -m unittest nunja.serve.tests.make_suite
  - coverage report -m

artifacts:
  - path: dist\*

build: off
