environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "4.6"
      BROWSER: "PhantomJS"
    - PYTHON: "C:\\Python33"
      nodejs_version: "4.6"
      BROWSER: "Firefox"
    - PYTHON: "C:\\Python34"
      nodejs_version: "6.9"
      BROWSER: "PhantomJS"
    - PYTHON: "C:\\Python35"
      nodejs_version: "6.9"
      BROWSER: "Firefox"
    - PYTHON: "C:\\Python36"
      nodejs_version: "7.4"
      BROWSER: "IE"
matrix:
  allow_failures:
    - BROWSER: "IE"

install:
  - choco install firefox
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"

  - pip install coverage calmjs
  - pip install -e git+https://github.com/calmjs/nunja.git#egg=nunja
  - python setup.py develop

test_script:
  - coverage run -m unittest nunja.serve.tests.make_suite
  - coverage report -m

artifacts:
  - path: dist\*

build: off
